export default {
  GATEWAY: 'GATEWAY',
  EMAIL_AUTH: 'EMAIL_AUTH',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  SEND_RESET_PASSWORD_MAIL: 'SEND_RESET_PASSWORD_MAIL',
  RESET_PASSWORD_INPUT_CODE: 'RESET_PASSWORD_INPUT_CODE',
  ENTER_NEW_PASSWORD: 'ENTER_NEW_PASSWORD',
  SUCCESS: 'SUCCESS'
}
